name: Spanish ¡Ole!
favicon: null
layout_spectrum: 0.4235783964395523
typography_spectrum: 0.83543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.6732641418930143
purpose: []
